import { apiClient } from "./client";
export interface Warehouse { id:string; code:string; name:string; phone?:string; address?:string; status:"ACTIVE"|"INACTIVE"; }
export interface Supplier { id:string; supplierCode:string; name:string; taxCode?:string; contactName?:string; phone?:string; email?:string; address?:string; status:"ACTIVE"|"INACTIVE"; }
export interface Balance { warehouseId:string; warehouseName:string; variantId:string; productName:string; sku:string; variantName:string; imageUrl?:string; onHandQuantity:number; reservedQuantity:number; availableQuantity:number; reorderLevel:number; updatedAt?:string; }
export interface ProcurementProductVariant { id:string; sku:string; name:string; suggestedUnitCost:number; }
export interface StockHistory { id:number; transactionType:string; quantity:number; onHandBefore:number; onHandAfter:number; warehouseName:string; sku:string; productName:string; referenceType:string; referenceId?:string; reason?:string; createdBy?:string; createdAt?:string; }
export interface InventoryUnitSummary { id:number; unitStatus:string; identifiers:string[]; receivedAt?:string; soldAt?:string; }
export interface InventoryUnitDetail { id:number; productName:string; variantName:string; sku:string; imageUrl?:string; warehouseName:string; unitStatus:string; receivedAt?:string; soldAt?:string; identifiers:{type:string;value:string}[]; origin?:{purchaseOrderCode?:string;purchaseOrderId?:string;receivedAt?:string}; reservation?:{id:number;orderId:string;status:string;expiresAt?:string;releasedAt?:string}; sale?:{orderCode?:string;orderItemId:string;soldAt?:string}; history:{id:number;transactionType:string;referenceType:string;referenceId?:string;reason?:string;createdBy?:string;createdAt?:string}[]; }
export interface InventoryEntity { id:number; warehouseId:string; variantId:string; productName:string; brandName?:string; variantName:string; sku:string; imageUrl?:string; warehouseName:string; unitStatus:string; maskedIdentifier?:string; identifierTypes:string[]; receivedAt?:string; soldAt?:string; }
export interface PageInfo { number:number; size:number; totalElements:number; totalPages:number; }
export interface Paged<T>{items:T[];page:PageInfo}
export interface WarehouseOverview { warehouse:Warehouse; skuCount:number; onHandQuantity:number; reservedQuantity:number; availableQuantity:number; balances:Balance[]; recentLedger:{id:number;transactionType:string;quantity:number;sku:string;productName:string;referenceType:string;referenceId?:string;createdBy?:string;createdAt?:string}[]; }
export const adminInventoryService={
 warehouses:()=>apiClient.get<Paged<Warehouse>>("/admin/inventory/warehouses").then(r=>r.data.items), createWarehouse:(data:Omit<Warehouse,"id"|"status">)=>apiClient.post<Warehouse>("/admin/inventory/warehouses",data).then(r=>r.data), warehouseStatus:(id:string,status:string)=>apiClient.patch<Warehouse>(`/admin/inventory/warehouses/${id}/status`,undefined,{params:{status}}).then(r=>r.data),
 warehouse:(id:string)=>apiClient.get<Warehouse>(`/admin/inventory/warehouses/${id}`).then(r=>r.data), warehouseOverview:(id:string)=>apiClient.get<WarehouseOverview>(`/admin/inventory/warehouses/${id}/overview`).then(r=>r.data),
 suppliers:()=>apiClient.get<Paged<Supplier>>("/admin/inventory/suppliers").then(r=>r.data.items), supplier:(id:string)=>apiClient.get<Supplier>(`/admin/inventory/suppliers/${id}`).then(r=>r.data), createSupplier:(data:Omit<Supplier,"id"|"status">)=>apiClient.post<Supplier>("/admin/inventory/suppliers",data).then(r=>r.data), updateSupplier:(id:string,data:Omit<Supplier,"id"|"status">)=>apiClient.put<Supplier>(`/admin/inventory/suppliers/${id}`,data).then(r=>r.data), supplierStatus:(id:string,status:string)=>apiClient.patch<Supplier>(`/admin/inventory/suppliers/${id}/status`,undefined,{params:{status}}).then(r=>r.data),
 productVariants:()=>apiClient.get<ProcurementProductVariant[]>("/admin/inventory/product-variants").then(r=>r.data),
 balances:()=>apiClient.get<Balance[]>("/admin/inventory/balances").then(r=>r.data), alerts:()=>apiClient.get<Balance[]>("/admin/inventory/reorder-alerts").then(r=>r.data), stockHistory:()=>apiClient.get<StockHistory[]>("/admin/inventory/stock-history").then(r=>r.data),
 inventoryUnits:(warehouseId:string,variantId:string)=>apiClient.get<InventoryUnitSummary[]>("/admin/inventory/units",{params:{warehouseId,variantId}}).then(r=>r.data), inventoryUnitDetail:(unitId:string|number)=>apiClient.get<InventoryUnitDetail>(`/admin/inventory/units/${unitId}`).then(r=>r.data),
 inventoryEntities:(params:{warehouseId?:string;status?:string;keyword?:string;page?:number;size?:number})=>apiClient.get<Paged<InventoryEntity>>("/admin/inventory/entities",{params}).then(r=>r.data), stockLedger:(params:{warehouseId?:string;transactionType?:string;keyword?:string;page?:number;size?:number})=>apiClient.get<Paged<StockHistory>>("/admin/inventory/stock-ledger",{params}).then(r=>r.data), adjustment:(data:{warehouseId:string;productVariantId:string;direction:"ADJUST_IN"|"ADJUST_OUT";quantity:number;reason:string;identifiers?:string[]})=>apiClient.post("/admin/inventory/adjustments",data,{headers:{"X-Idempotency-Key":crypto.randomUUID()}}),
};
