import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, CheckCircle2, ChevronRight, CircleHelp, Headphones, Search, Send } from "lucide-react";
import { message } from "antd";
import { Link, useNavigate, useParams } from "react-router-dom";
import { adminSettingsSupportService, type SupportArticle } from "../../api/adminSettingsSupportService";

function ArticleIcon({ category }: { category: string }) { return <span className="grid h-11 w-11 place-items-center rounded-xl bg-[#ffe4eb] text-[#c2185b]">{category.includes("lỗi") ? <CircleHelp size={21} /> : category.includes("vận hành") ? <CheckCircle2 size={21} /> : <BookOpen size={21} />}</span>; }

function MarkdownContent({ content }: { content: string }) {
  return <div className="space-y-4 text-[15px] leading-7 text-slate-700">{content.split("\n").map((line, index) => { const key = `${index}-${line}`; if (line.startsWith("# ")) return <h1 key={key} className="text-3xl font-black leading-tight text-slate-950">{line.slice(2)}</h1>; if (line.startsWith("## ")) return <h2 key={key} className="pt-4 text-xl font-black text-slate-950">{line.slice(3)}</h2>; if (line.startsWith("- ")) return <li key={key} className="ml-5 list-disc">{line.slice(2)}</li>; if (!line.trim()) return <div key={key} className="h-1" />; return <p key={key}>{line}</p>; })}</div>;
}

function TicketForm() {
  const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [priority, setPriority] = useState("MEDIUM"); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!subject.trim() || !description.trim()) { message.warning("Vui lòng nhập tiêu đề và mô tả sự cố."); return; } setSaving(true); try { await adminSettingsSupportService.createTicket({ subject, description, priority }); message.success("Đã gửi yêu cầu hỗ trợ."); setSubject(""); setDescription(""); } catch { message.error("Không thể gửi yêu cầu hỗ trợ."); } finally { setSaving(false); } };
  return <section className="rounded-2xl border border-[#eadbe1] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0f5] text-[#d81b60]"><Headphones size={20} /></span><div><h2 className="text-xl font-black text-slate-950">Gửi yêu cầu hỗ trợ</h2><p className="text-sm text-slate-500">Mô tả chi tiết để đội kỹ thuật xử lý nhanh nhất.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Tiêu đề yêu cầu<input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Ví dụ: Không thể lưu phiếu nhập" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-[#d81b60]" /></label><label className="text-sm font-semibold">Mức độ ưu tiên<select value={priority} onChange={(event) => setPriority(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal"><option value="LOW">Thấp</option><option value="MEDIUM">Trung bình</option><option value="HIGH">Cao</option><option value="URGENT">Khẩn cấp</option></select></label></div><label className="mt-4 block text-sm font-semibold">Mô tả chi tiết<textarea rows={5} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Mô tả các bước tái hiện, mã đơn hàng hoặc correlation ID nếu có…" className="mt-1.5 w-full resize-y rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-[#d81b60]" /></label><div className="mt-4 flex justify-end"><button disabled={saving} onClick={() => void submit()} className="inline-flex items-center gap-2 rounded-lg bg-[#c2185b] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60"><Send size={16} /> {saving ? "Đang gửi…" : "Gửi yêu cầu"}</button></div></section>;
}

export function AdminSupportPage(_props?: { title?: string; description?: string }) {
  const [articles, setArticles] = useState<SupportArticle[]>([]); const [query, setQuery] = useState("");
  useEffect(() => { adminSettingsSupportService.getArticles().then(setArticles).catch(() => message.error("Không tải được tài liệu hỗ trợ.")); }, []);
  const filtered = useMemo(() => articles.filter((article) => `${article.title} ${article.summary} ${article.category}`.toLowerCase().includes(query.toLowerCase())), [articles, query]);
  return <div className="mx-auto max-w-[1200px] space-y-7"><section className="rounded-2xl bg-gradient-to-br from-[#fff0f4] to-white px-5 py-10 text-center"><h1 className="text-4xl font-black text-slate-950">Trung tâm Hỗ trợ & Tài liệu</h1><p className="mx-auto mt-3 max-w-2xl text-slate-600">Tìm câu trả lời hoặc gửi yêu cầu hỗ trợ trực tiếp đến đội ngũ kỹ thuật.</p><label className="mx-auto mt-7 flex max-w-2xl items-center gap-3 rounded-full border border-[#edcbd7] bg-white px-5 py-3 text-slate-400 shadow-sm"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nhập từ khóa tìm kiếm tài liệu hướng dẫn…" className="w-full bg-transparent outline-none" /></label></section><section><h2 className="text-2xl font-black text-slate-950">Chủ đề phổ biến</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{filtered.map((article) => <Link key={article.slug} to={`/admin/support/${article.slug}`} className="group rounded-2xl border border-[#efd9e1] bg-[#fff5f6] p-5 transition hover:-translate-y-1 hover:border-[#e6a9bd] hover:shadow-md"><ArticleIcon category={article.category} /><div className="mt-4 text-xs font-bold uppercase tracking-wide text-[#c2185b]">{article.category}</div><h3 className="mt-2 text-xl font-bold text-slate-950">{article.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{article.summary}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#c2185b]">Xem chi tiết <ChevronRight size={16} className="transition group-hover:translate-x-1" /></span></Link>)}</div>{!filtered.length && <div className="mt-4 rounded-xl border border-dashed p-8 text-center text-slate-500">Không tìm thấy chủ đề phù hợp.</div>}</section><div className="grid gap-5 lg:grid-cols-[0.75fr_1.5fr]"><aside className="rounded-2xl bg-[#fff0f2] p-6"><Headphones className="text-[#c2185b]" size={25} /><h2 className="mt-3 text-xl font-black">Liên hệ trực tiếp</h2><p className="mt-2 text-sm leading-6 text-slate-600">Đội kỹ thuật luôn sẵn sàng giải đáp các sự cố nghiêm trọng.</p><div className="mt-5 rounded-xl bg-white p-4"><div className="text-xs font-bold uppercase text-slate-500">Hỗ trợ kỹ thuật</div><div className="mt-1 text-xl font-black text-slate-950">1900 1234</div><div className="mt-1 text-sm text-slate-500">24/7 cho sự cố nghiêm trọng</div></div></aside><TicketForm /></div></div>;
}

export function AdminSupportArticlePage() {
  const { slug } = useParams(); const navigate = useNavigate(); const [article, setArticle] = useState<SupportArticle>();
  useEffect(() => { if (!slug) return; adminSettingsSupportService.getArticle(slug).then(setArticle).catch(() => { message.error("Không tìm thấy tài liệu."); navigate("/admin/support"); }); }, [slug, navigate]);
  if (!article) return <div className="p-12 text-center text-slate-500">Đang tải tài liệu…</div>;
  return <div className="mx-auto max-w-[1200px]"><button onClick={() => navigate("/admin/support")} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[#c2185b]"><ArrowLeft size={17} /> Trung tâm hỗ trợ</button><div className="grid gap-6 lg:grid-cols-[1fr_310px]"><article className="rounded-2xl border border-[#eadbe1] bg-white p-6 shadow-sm md:p-9"><div className="flex flex-wrap items-center gap-3 text-xs text-slate-500"><span className="rounded-full bg-[#fff0f5] px-3 py-1 font-bold text-[#c2185b]">{article.category}</span><span>•</span><span>{article.views.toLocaleString("vi-VN")} lượt xem</span></div><div className="mt-5 border-b border-slate-100 pb-7"><h1 className="text-3xl font-black leading-tight text-slate-950">{article.title}</h1><p className="mt-3 text-base leading-7 text-slate-500">{article.summary}</p></div><div className="mt-7"><MarkdownContent content={article.content || ""} /></div></article><aside className="space-y-4"><div className="sticky top-24 rounded-2xl border border-[#eadbe1] bg-[#fff7f8] p-5"><h2 className="font-black text-slate-950">Mục lục nội dung</h2><div className="mt-4 space-y-2 text-sm text-[#c2185b]">{(article.content || "").split("\n").filter((line) => line.startsWith("#")).map((line) => <div key={line}>{line.replace(/^#+\s*/, "")}</div>)}</div></div><div className="rounded-2xl border border-[#eadbe1] bg-white p-5"><h2 className="font-black text-slate-950">Cần hỗ trợ thêm?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Gửi ticket để đội kỹ thuật tiếp nhận.</p><Link to="/admin/support#ticket" className="mt-4 inline-flex w-full items-center justify-center rounded-lg border border-[#d81b60] px-3 py-2 text-sm font-bold text-[#d81b60]">Gửi yêu cầu hỗ trợ</Link></div></aside></div></div>;
}
